version: "3.8"
services:
  server:
    build: 
      context: ./
      dockerfile: server.Dockerfile
    container_name: server
    # environment:
      # - PUID=1000
    ports: 
      - 8080:8080
    # restart: unless-stopped

  client:
    build: 
      context: ./
      dockerfile: client.Dockerfile
    container_name: client
    ports: 
      - 3000:3000

  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
