version: "3.8"
services:
  server:
    build: 
      context: ./
      dockerfile: server.Dockerfile
    container_name: server
    # environment:
      # - PUID=1000
    ports: 
      - 8080:8080
    # restart: unless-stopped

  client:
    build: 
      context: ./
      dockerfile: client.Dockerfile
    container_name: client
    ports: 
      - 3000:3000
