"use client";

/**
 * Content of this file taken directly from
 * "node_modules/@mui/material/index.js". This allows, to my belief, for tree
 * shaking of the library.
 */

import * as colors from "node_modules/@mui/material/colors";

export { colors };

export * from "node_modules/@mui/material/styles";
export * from "node_modules/@mui/material/utils";
export { default as Accordion } from "node_modules/@mui/material/Accordion";
export * from "node_modules/@mui/material/Accordion";
export { default as AccordionActions } from "node_modules/@mui/material/AccordionActions";
export * from "node_modules/@mui/material/AccordionActions";
export { default as AccordionDetails } from "node_modules/@mui/material/AccordionDetails";
export * from "node_modules/@mui/material/AccordionDetails";
export { default as AccordionSummary } from "node_modules/@mui/material/AccordionSummary";
export * from "node_modules/@mui/material/AccordionSummary";
export { default as Alert } from "node_modules/@mui/material/Alert";
export * from "node_modules/@mui/material/Alert";
export { default as AlertTitle } from "node_modules/@mui/material/AlertTitle";
export * from "node_modules/@mui/material/AlertTitle";
export { default as AppBar } from "node_modules/@mui/material/AppBar";
export * from "node_modules/@mui/material/AppBar";
export { default as Autocomplete } from "node_modules/@mui/material/Autocomplete";
export * from "node_modules/@mui/material/Autocomplete";
export { default as Avatar } from "node_modules/@mui/material/Avatar";
export * from "node_modules/@mui/material/Avatar";
export { default as AvatarGroup } from "node_modules/@mui/material/AvatarGroup";
export * from "node_modules/@mui/material/AvatarGroup";
export { default as Backdrop } from "node_modules/@mui/material/Backdrop";
export * from "node_modules/@mui/material/Backdrop";
export { default as Badge } from "node_modules/@mui/material/Badge";
export * from "node_modules/@mui/material/Badge";
export { default as BottomNavigation } from "node_modules/@mui/material/BottomNavigation";
export * from "node_modules/@mui/material/BottomNavigation";
export { default as BottomNavigationAction } from "node_modules/@mui/material/BottomNavigationAction";
export * from "node_modules/@mui/material/BottomNavigationAction";
export { default as Box } from "node_modules/@mui/material/Box";
export * from "node_modules/@mui/material/Box";
export { default as Breadcrumbs } from "node_modules/@mui/material/Breadcrumbs";
export * from "node_modules/@mui/material/Breadcrumbs";
export { default as Button } from "node_modules/@mui/material/Button";
export * from "node_modules/@mui/material/Button";
export { default as ButtonBase } from "node_modules/@mui/material/ButtonBase";
export * from "node_modules/@mui/material/ButtonBase";
export { default as ButtonGroup } from "node_modules/@mui/material/ButtonGroup";
export * from "node_modules/@mui/material/ButtonGroup";
export { default as Card } from "node_modules/@mui/material/Card";
export * from "node_modules/@mui/material/Card";
export { default as CardActionArea } from "node_modules/@mui/material/CardActionArea";
export * from "node_modules/@mui/material/CardActionArea";
export { default as CardActions } from "node_modules/@mui/material/CardActions";
export * from "node_modules/@mui/material/CardActions";
export { default as CardContent } from "node_modules/@mui/material/CardContent";
export * from "node_modules/@mui/material/CardContent";
export { default as CardHeader } from "node_modules/@mui/material/CardHeader";
export * from "node_modules/@mui/material/CardHeader";
export { default as CardMedia } from "node_modules/@mui/material/CardMedia";
export * from "node_modules/@mui/material/CardMedia";
export { default as Checkbox } from "node_modules/@mui/material/Checkbox";
export * from "node_modules/@mui/material/Checkbox";
export { default as Chip } from "node_modules/@mui/material/Chip";
export * from "node_modules/@mui/material/Chip";
export { default as CircularProgress } from "node_modules/@mui/material/CircularProgress";
export * from "node_modules/@mui/material/CircularProgress";
export { default as ClickAwayListener } from "node_modules/@mui/material/ClickAwayListener";
export * from "node_modules/@mui/material/ClickAwayListener";
export { default as Collapse } from "node_modules/@mui/material/Collapse";
export * from "node_modules/@mui/material/Collapse";
export { default as Container } from "node_modules/@mui/material/Container";
export * from "node_modules/@mui/material/Container";
export { default as CssBaseline } from "node_modules/@mui/material/CssBaseline";
export * from "node_modules/@mui/material/CssBaseline";
export { default as darkScrollbar } from "node_modules/@mui/material/darkScrollbar";
export { default as Dialog } from "node_modules/@mui/material/Dialog";
export * from "node_modules/@mui/material/Dialog";
export { default as DialogActions } from "node_modules/@mui/material/DialogActions";
export * from "node_modules/@mui/material/DialogActions";
export { default as DialogContent } from "node_modules/@mui/material/DialogContent";
export * from "node_modules/@mui/material/DialogContent";
export { default as DialogContentText } from "node_modules/@mui/material/DialogContentText";
export * from "node_modules/@mui/material/DialogContentText";
export { default as DialogTitle } from "node_modules/@mui/material/DialogTitle";
export * from "node_modules/@mui/material/DialogTitle";
export { default as Divider } from "node_modules/@mui/material/Divider";
export * from "node_modules/@mui/material/Divider";
export { default as Drawer } from "node_modules/@mui/material/Drawer";
export * from "node_modules/@mui/material/Drawer";
export { default as Fab } from "node_modules/@mui/material/Fab";
export * from "node_modules/@mui/material/Fab";
export { default as Fade } from "node_modules/@mui/material/Fade";
export * from "node_modules/@mui/material/Fade";
export { default as FilledInput } from "node_modules/@mui/material/FilledInput";
export * from "node_modules/@mui/material/FilledInput";
export { default as FormControl } from "node_modules/@mui/material/FormControl";
export * from "node_modules/@mui/material/FormControl";
export { default as FormControlLabel } from "node_modules/@mui/material/FormControlLabel";
export * from "node_modules/@mui/material/FormControlLabel";
export { default as FormGroup } from "node_modules/@mui/material/FormGroup";
export * from "node_modules/@mui/material/FormGroup";
export { default as FormHelperText } from "node_modules/@mui/material/FormHelperText";
export * from "node_modules/@mui/material/FormHelperText";
export { default as FormLabel } from "node_modules/@mui/material/FormLabel";
export * from "node_modules/@mui/material/FormLabel";
export { default as Grid } from "node_modules/@mui/material/Grid";
export * from "node_modules/@mui/material/Grid";
export { default as Unstable_Grid2 } from "node_modules/@mui/material/Unstable_Grid2";
export * from "node_modules/@mui/material/Unstable_Grid2";
export { default as Grow } from "node_modules/@mui/material/Grow";
export * from "node_modules/@mui/material/Grow";
export { default as Hidden } from "node_modules/@mui/material/Hidden";
export * from "node_modules/@mui/material/Hidden";
export { default as Icon } from "node_modules/@mui/material/Icon";
export * from "node_modules/@mui/material/Icon";
export { default as IconButton } from "node_modules/@mui/material/IconButton";
export * from "node_modules/@mui/material/IconButton";
export { default as ImageList } from "node_modules/@mui/material/ImageList";
export * from "node_modules/@mui/material/ImageList";
export { default as ImageListItem } from "node_modules/@mui/material/ImageListItem";
export * from "node_modules/@mui/material/ImageListItem";
export { default as ImageListItemBar } from "node_modules/@mui/material/ImageListItemBar";
export * from "node_modules/@mui/material/ImageListItemBar";
export { default as Input } from "node_modules/@mui/material/Input";
export * from "node_modules/@mui/material/Input";
export { default as InputAdornment } from "node_modules/@mui/material/InputAdornment";
export * from "node_modules/@mui/material/InputAdornment";
export { default as InputBase } from "node_modules/@mui/material/InputBase";
export * from "node_modules/@mui/material/InputBase";
export { default as InputLabel } from "node_modules/@mui/material/InputLabel";
export * from "node_modules/@mui/material/InputLabel";
export { default as LinearProgress } from "node_modules/@mui/material/LinearProgress";
export * from "node_modules/@mui/material/LinearProgress";
export { default as Link } from "node_modules/@mui/material/Link";
export * from "node_modules/@mui/material/Link";
export { default as List } from "node_modules/@mui/material/List";
export * from "node_modules/@mui/material/List";
export { default as ListItem } from "node_modules/@mui/material/ListItem";
export * from "node_modules/@mui/material/ListItem";
export { default as ListItemAvatar } from "node_modules/@mui/material/ListItemAvatar";
export * from "node_modules/@mui/material/ListItemAvatar";
export { default as ListItemButton } from "node_modules/@mui/material/ListItemButton";
export * from "node_modules/@mui/material/ListItemButton";
export { default as ListItemIcon } from "node_modules/@mui/material/ListItemIcon";
export * from "node_modules/@mui/material/ListItemIcon";
export { default as ListItemSecondaryAction } from "node_modules/@mui/material/ListItemSecondaryAction";
export * from "node_modules/@mui/material/ListItemSecondaryAction";
export { default as ListItemText } from "node_modules/@mui/material/ListItemText";
export * from "node_modules/@mui/material/ListItemText";
export { default as ListSubheader } from "node_modules/@mui/material/ListSubheader";
export * from "node_modules/@mui/material/ListSubheader";
export { default as Menu } from "node_modules/@mui/material/Menu";
export * from "node_modules/@mui/material/Menu";
export { default as MenuItem } from "node_modules/@mui/material/MenuItem";
export * from "node_modules/@mui/material/MenuItem";
export { default as MenuList } from "node_modules/@mui/material/MenuList";
export * from "node_modules/@mui/material/MenuList";
export { default as MobileStepper } from "node_modules/@mui/material/MobileStepper";
export * from "node_modules/@mui/material/MobileStepper";
export { default as Modal } from "node_modules/@mui/material/Modal";
export * from "node_modules/@mui/material/Modal";
export { default as NativeSelect } from "node_modules/@mui/material/NativeSelect";
export * from "node_modules/@mui/material/NativeSelect";
export { default as NoSsr } from "node_modules/@mui/material/NoSsr";
export * from "node_modules/@mui/material/NoSsr";
export { default as OutlinedInput } from "node_modules/@mui/material/OutlinedInput";
export * from "node_modules/@mui/material/OutlinedInput";
export { default as Pagination } from "node_modules/@mui/material/Pagination";
export * from "node_modules/@mui/material/Pagination";
export { default as PaginationItem } from "node_modules/@mui/material/PaginationItem";
export * from "node_modules/@mui/material/PaginationItem";
export { default as Paper } from "node_modules/@mui/material/Paper";
export * from "node_modules/@mui/material/Paper";
export { default as Popover } from "node_modules/@mui/material/Popover";
export * from "node_modules/@mui/material/Popover";
export { default as Popper } from "node_modules/@mui/material/Popper";
export * from "node_modules/@mui/material/Popper";
export { default as Portal } from "node_modules/@mui/material/Portal";
export * from "node_modules/@mui/material/Portal";
export { default as Radio } from "node_modules/@mui/material/Radio";
export * from "node_modules/@mui/material/Radio";
export { default as RadioGroup } from "node_modules/@mui/material/RadioGroup";
export * from "node_modules/@mui/material/RadioGroup";
export { default as Rating } from "node_modules/@mui/material/Rating";
export * from "node_modules/@mui/material/Rating";
export { default as ScopedCssBaseline } from "node_modules/@mui/material/ScopedCssBaseline";
export * from "node_modules/@mui/material/ScopedCssBaseline";
export { default as Select } from "node_modules/@mui/material/Select";
export * from "node_modules/@mui/material/Select";
export { default as Skeleton } from "node_modules/@mui/material/Skeleton";
export * from "node_modules/@mui/material/Skeleton";
export { default as Slide } from "node_modules/@mui/material/Slide";
export * from "node_modules/@mui/material/Slide";
export { default as Slider } from "node_modules/@mui/material/Slider";
export * from "node_modules/@mui/material/Slider";
export { default as Snackbar } from "node_modules/@mui/material/Snackbar";
export * from "node_modules/@mui/material/Snackbar";
export { default as SnackbarContent } from "node_modules/@mui/material/SnackbarContent";
export * from "node_modules/@mui/material/SnackbarContent";
export { default as SpeedDial } from "node_modules/@mui/material/SpeedDial";
export * from "node_modules/@mui/material/SpeedDial";
export { default as SpeedDialAction } from "node_modules/@mui/material/SpeedDialAction";
export * from "node_modules/@mui/material/SpeedDialAction";
export { default as SpeedDialIcon } from "node_modules/@mui/material/SpeedDialIcon";
export * from "node_modules/@mui/material/SpeedDialIcon";
export { default as Stack } from "node_modules/@mui/material/Stack";
export * from "node_modules/@mui/material/Stack";
export { default as Step } from "node_modules/@mui/material/Step";
export * from "node_modules/@mui/material/Step";
export { default as StepButton } from "node_modules/@mui/material/StepButton";
export * from "node_modules/@mui/material/StepButton";
export { default as StepConnector } from "node_modules/@mui/material/StepConnector";
export * from "node_modules/@mui/material/StepConnector";
export { default as StepContent } from "node_modules/@mui/material/StepContent";
export * from "node_modules/@mui/material/StepContent";
export { default as StepIcon } from "node_modules/@mui/material/StepIcon";
export * from "node_modules/@mui/material/StepIcon";
export { default as StepLabel } from "node_modules/@mui/material/StepLabel";
export * from "node_modules/@mui/material/StepLabel";
export { default as Stepper } from "node_modules/@mui/material/Stepper";
export * from "node_modules/@mui/material/Stepper";
export { default as SvgIcon } from "node_modules/@mui/material/SvgIcon";
export * from "node_modules/@mui/material/SvgIcon";
export { default as SwipeableDrawer } from "node_modules/@mui/material/SwipeableDrawer";
export * from "node_modules/@mui/material/SwipeableDrawer";
export { default as Switch } from "node_modules/@mui/material/Switch";
export * from "node_modules/@mui/material/Switch";
export { default as Tab } from "node_modules/@mui/material/Tab";
export * from "node_modules/@mui/material/Tab";
export { default as Table } from "node_modules/@mui/material/Table";
export * from "node_modules/@mui/material/Table";
export { default as TableBody } from "node_modules/@mui/material/TableBody";
export * from "node_modules/@mui/material/TableBody";
export { default as TableCell } from "node_modules/@mui/material/TableCell";
export * from "node_modules/@mui/material/TableCell";
export { default as TableContainer } from "node_modules/@mui/material/TableContainer";
export * from "node_modules/@mui/material/TableContainer";
export { default as TableFooter } from "node_modules/@mui/material/TableFooter";
export * from "node_modules/@mui/material/TableFooter";
export { default as TableHead } from "node_modules/@mui/material/TableHead";
export * from "node_modules/@mui/material/TableHead";
export { default as TablePagination } from "node_modules/@mui/material/TablePagination";
export * from "node_modules/@mui/material/TablePagination";
export { default as TableRow } from "node_modules/@mui/material/TableRow";
export * from "node_modules/@mui/material/TableRow";
export { default as TableSortLabel } from "node_modules/@mui/material/TableSortLabel";
export * from "node_modules/@mui/material/TableSortLabel";
export { default as Tabs } from "node_modules/@mui/material/Tabs";
export * from "node_modules/@mui/material/Tabs";
export { default as TabScrollButton } from "node_modules/@mui/material/TabScrollButton";
export * from "node_modules/@mui/material/TabScrollButton";
export { default as TextField } from "node_modules/@mui/material/TextField";
export * from "node_modules/@mui/material/TextField";
export { default as TextareaAutosize } from "node_modules/@mui/material/TextareaAutosize";
export * from "node_modules/@mui/material/TextareaAutosize";
export { default as ToggleButton } from "node_modules/@mui/material/ToggleButton";
export * from "node_modules/@mui/material/ToggleButton";
export { default as ToggleButtonGroup } from "node_modules/@mui/material/ToggleButtonGroup";
export * from "node_modules/@mui/material/ToggleButtonGroup";
export { default as Toolbar } from "node_modules/@mui/material/Toolbar";
export * from "node_modules/@mui/material/Toolbar";
export { default as Tooltip } from "node_modules/@mui/material/Tooltip";
export * from "node_modules/@mui/material/Tooltip";
export { default as Typography } from "node_modules/@mui/material/Typography";
export * from "node_modules/@mui/material/Typography";
export { default as useMediaQuery } from "node_modules/@mui/material/useMediaQuery";
export * from "node_modules/@mui/material/useMediaQuery";
export { default as usePagination } from "node_modules/@mui/material/usePagination";
export * from "node_modules/@mui/material/usePagination";
export { default as useScrollTrigger } from "node_modules/@mui/material/useScrollTrigger";
export { default as Zoom } from "node_modules/@mui/material/Zoom";
export * from "node_modules/@mui/material/Zoom";

// createFilterOptions is exported from Autocomplete
export { default as useAutocomplete } from "node_modules/@mui/material/useAutocomplete";
export { default as GlobalStyles } from "node_modules/@mui/material/GlobalStyles";
export * from "node_modules/@mui/material/GlobalStyles";
export { default as generateUtilityClass } from "node_modules/@mui/material/generateUtilityClass";
export * from "node_modules/@mui/material/generateUtilityClass";
export { default as generateUtilityClasses } from "node_modules/@mui/material/generateUtilityClasses";
export { default as Unstable_TrapFocus } from "node_modules/@mui/material/Unstable_TrapFocus";
