import { faInfo } from "@fortawesome/free-solid-svg-icons";
import { ReactElement } from "react";

import { Button } from "@components/form/button";
import { IconButton } from "@components/form/icon-button";
import { ToggleButton } from "@components/form/toggle-button";
import { Card } from "@components/misc/card";
import { Type } from "@components/type";
import { Heading } from "@components/typography/heading";
import { Paragraph } from "@components/typography/paragraph";
import { Section } from "@components/typography/section";
import { Subheading } from "@components/typography/subheading";
import { Title } from "@components/typography/title";
import { Variant } from "@components/variant";

const Components = (): ReactElement => (
    <Card>
        <Title>
            Components
        </Title>
        <Section>
            <Heading>
                Button
            </Heading>
            <Paragraph>
                <Button
                    ariaLabel="Default"
                    label="Default"
                />
            </Paragraph>
            <Paragraph>
                <Subheading>
                    Filled
                </Subheading>
                <Button
                    ariaLabel="Default"
                    label="Default"
                    type={Type.Filled}
                />
                <Button
                    ariaLabel="Info"
                    label="Info"
                    type={Type.Filled}
                    variant={Variant.Info}
                />
                <Button
                    ariaLabel="Success"
                    label="Success"
                    type={Type.Filled}
                    variant={Variant.Success}
                />
                <Button
                    ariaLabel="Warning"
                    label="Warning"
                    type={Type.Filled}
                    variant={Variant.Warning}
                />
                <Button
                    ariaLabel="Error"
                    label="Error"
                    type={Type.Filled}
                    variant={Variant.Error}
                />
            </Paragraph>
            <Paragraph>
                <Subheading>
                    Filled Tonal
                </Subheading>
                <Button
                    ariaLabel="Default"
                    label="Default"
                    type={Type.FilledTonal}
                />
                <Button
                    ariaLabel="Info"
                    label="Info"
                    type={Type.FilledTonal}
                    variant={Variant.Info}
                />
                <Button
                    ariaLabel="Success"
                    label="Success"
                    type={Type.FilledTonal}
                    variant={Variant.Success}
                />
                <Button
                    ariaLabel="Warning"
                    label="Warning"
                    type={Type.FilledTonal}
                    variant={Variant.Warning}
                />
                <Button
                    ariaLabel="Error"
                    label="Error"
                    type={Type.FilledTonal}
                    variant={Variant.Error}
                />
            </Paragraph>
            <Paragraph>
                <Subheading>
                    Outlined
                </Subheading>
                <Button
                    ariaLabel="Default"
                    label="Default"
                    type={Type.Outlined}
                />
                <Button
                    ariaLabel="Info"
                    label="Info"
                    type={Type.Outlined}
                    variant={Variant.Info}
                />
                <Button
                    ariaLabel="Success"
                    label="Success"
                    type={Type.Outlined}
                    variant={Variant.Success}
                />
                <Button
                    ariaLabel="Warning"
                    label="Warning"
                    type={Type.Outlined}
                    variant={Variant.Warning}
                />
                <Button
                    ariaLabel="Error"
                    label="Error"
                    type={Type.Outlined}
                    variant={Variant.Error}
                />
            </Paragraph>
            <Paragraph>
                <Subheading>
                    Text
                </Subheading>
                <Button
                    ariaLabel="Default"
                    label="Default"
                    type={Type.Text}
                />
                <Button
                    ariaLabel="Info"
                    label="Info"
                    type={Type.Text}
                    variant={Variant.Info}
                />
                <Button
                    ariaLabel="Success"
                    label="Success"
                    type={Type.Text}
                    variant={Variant.Success}
                />
                <Button
                    ariaLabel="Warning"
                    label="Warning"
                    type={Type.Text}
                    variant={Variant.Warning}
                />
                <Button
                    ariaLabel="Error"
                    label="Error"
                    type={Type.Text}
                    variant={Variant.Error}
                />
            </Paragraph>
        </Section>
        <Section>
            <Heading>
                Toggle Button
            </Heading>
            <Paragraph>
                <ToggleButton
                    ariaLabel="Default"
                    label="Default"
                    isActive={false}
                />
            </Paragraph>
            <Paragraph>
                <Subheading>
                    Filled
                </Subheading>
                <ToggleButton
                    ariaLabel="Default"
                    label="Default"
                    isActive={false}
                />
                <ToggleButton
                    ariaLabel="Default"
                    label="Default"
                    isActive
                />
                <ToggleButton
                    ariaLabel="Info"
                    label="Info"
                    isActive={false}
                    variant={Variant.Info}
                />
                <ToggleButton
                    ariaLabel="Info"
                    label="Info"
                    isActive
                    variant={Variant.Info}
                />
                <ToggleButton
                    ariaLabel="Success"
                    label="Success"
                    isActive={false}
                    variant={Variant.Success}
                />
                <ToggleButton
                    ariaLabel="Success"
                    label="Success"
                    isActive
                    variant={Variant.Success}
                />
                <ToggleButton
                    ariaLabel="Warning"
                    label="Warning"
                    isActive={false}
                    variant={Variant.Warning}
                />
                <ToggleButton
                    ariaLabel="Warning"
                    label="Warning"
                    isActive
                    variant={Variant.Warning}
                />
                <ToggleButton
                    ariaLabel="Error"
                    label="Error"
                    isActive={false}
                    variant={Variant.Error}
                />
                <ToggleButton
                    ariaLabel="Error"
                    label="Error"
                    isActive
                    variant={Variant.Error}
                />
            </Paragraph>
        </Section>
        <Section>
            <Heading>
                Icon Button
            </Heading>
            <Paragraph>
                <IconButton
                    // eslint-disable-next-line @typescript-eslint/no-empty-function
                    onClick={(): void => { }}
                    ariaLabel="Default"
                    icon={faInfo}
                />
            </Paragraph>
        </Section>
    </Card >
);

export default Components;
