name: Testing Workflow

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize
        uses: ./.github/actions/initialize/

      - name: Lint
        run: pnpm run lint

  test-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize
        uses: ./.github/actions/initialize/

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Unit testing
        run: pnpm run test

  test-mutation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize
        uses: ./.github/actions/initialize/

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Setup Stryker cache
        uses: actions/cache@v3
        with:
          path: ./reports/stryker-incremental.json
          key: ${{ runner.os }}-stryker

      - name: Mutation testing
        run: pnpm run test:mutation
